# Default values for multi-container-app-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ministryofjustice/cloud-platform-multi-container-demo-app
  tag: worker-1.4
  pullPolicy: IfNotPresent
containerPort: 4567
postgresurl: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

