# Default values for multi-container-app-content-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ministryofjustice/cloud-platform-multi-container-demo-app
  tag: content-api-1.4
  pullPolicy: IfNotPresent
containerPort: 4567

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 4567
  targetPort: 4567