version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: demo

jobs:
  build:
    docker:
    - image: ${ECR_ENDPOINT}/imran-test/test:tools-circleci
      environment:
        IMAGE_URI: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/imran-test/test:rails
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build application Docker image
        command: |
          echo ${KUBE_ENV_NAMESPACE}