version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: demo

jobs:
  build:
    docker:
    - image: ${ECR_ENDPOINT}/imran-test/test:tools-circleci
      environment:
        IMAGE_URI: ${ECR_ENDPOINT}/imran-test/test:rails
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build application Docker image and push to ECR
        command: |
          $(aws ecr get-login --no-include-email)
          docker build -t ${IMAGE_URI} .
          docker push ${IMAGE_URI}