version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: demo
jobs:
  build:
    docker:
    - image: ${ECR_ENDPOINT}/cloud-platform/tools:circleci-internal
      environment:
        IMAGE_URI: ${ECR_ENDPOINT}/imran-test/test:rails
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build application Docker image and push to ECR
        command: |
          $(aws ecr get-login --no-include-email)
          docker build -t 754256621582.dkr.ecr.eu-west-2.amazonaws.com/imran-test/test:rails rails-app
          docker push 754256621582.dkr.ecr.eu-west-2.amazonaws.com/imran-test/test:rails
    - run:
        name: Authenticate with cluster
        command: |
          echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
          kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=https://api.${K8S_CLUSTER_NAME}
          kubectl config set-credentials circleci --token=${K8S_TOKEN}
          kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=${K8S_NAMESPACE}
          kubectl config use-context ${K8S_CLUSTER_NAME}
    - run:
        name: Install demo helm chart
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            helm upgrade demo-app helm-test --install --namespace=${K8S_NAMESPACE}
          fi 
          kubectl --namespace=${K8S_NAMESPACE} get pods


          