version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: demo

jobs:
  build:
    docker:
    - image: ${ECR_ENDPOINT}/imran-test/test:tools-circleci
      environment:
        IMAGE_URI: ${ECR_ENDPOINT}/imran-test/test:rails
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build application Docker image and push to ECR
        command: |
          $(aws ecr get-login --no-include-email)
          docker build -t 754256621582.dkr.ecr.eu-west-2.amazonaws.com/imran-test/test:rails rails-app
          docker push 754256621582.dkr.ecr.eu-west-2.amazonaws.com/imran-test/test:rails



          