apiVersion: v1
kind: Secret
metadata:
  name: container-postgres-secrets
data:
  # username: myuser, password: password123
  # https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#add-http-basic-authentication
  postgresql-postgres-password: <password>
  postgresql-password: <password>