# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 11.7.0-debian-10-r9

existingSecret: container-postgres-secrets

postgresqlDatabase: multi_container_demo_app

persistence:
  enabled: false