apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: ministryofjustice/cloud-platform-multi-container-demo-app:worker-1.4
        ports:
        - containerPort: 4567
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-multi-container-demo-dev
                key: url

